CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    public_link VARCHAR(255) UNIQUE,
    balance DECIMAL(10,2) DEFAULT 0.00
); 